version: '3.8'

services:
  # Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: h3ds_db
    restart: always
    environment:
      POSTGRES_DB: happy3DShop
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - ./Backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Solo para acceso externo si es necesario, puede quitarse en prod
    networks:
      - h3ds_net

  # Backend: Spring Boot
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: h3ds_backend
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080" # Expuesto para APIs y acceso local
    env_file:
      - ./Backend/.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/happy3DShop
    networks:
      - h3ds_net

  # Frontend: React + Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://40.233.15.187:8080
    container_name: h3ds_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80" # El tráfico principal web entra por aquí
    networks:
      - h3ds_net

volumes:
  postgres_data:
    name: h3ds_postgres_data

networks:
  h3ds_net:
    name: h3ds_network
    driver: bridge
